# Learn Pandas

In [1]:
import pandas as pd

# Read CSV

In [10]:
df = pd.read_csv("./data/housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

# Read Xlsx

In [13]:
pd.read_excel("./data/housing.xlsx", engine="openpyxl").head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,3252-08-01 00:00:00,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,3014-08-01 00:00:00,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,2574-07-01 00:00:00,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,6431-05-01 00:00:00,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,8462-03-01 00:00:00,342200.0,NEAR BAY

# Read CSV from URL

In [15]:
data =pd.read_csv("https://raw.githubusercontent.com/freeCodeCamp/open-data/master/medium-fCC-data/data/medium_titles%20-%20rawdata.tsv", sep="\t")

In [21]:
data.sample(5)

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
296,114,539,0.0,It’s time to get in over your headIn freeCodeC...,It’s time to get in over your head,529,MOT,529.0,0.0,0.0
617,474,179,0.0,In Honor of National Grammar DayIn freeCodeCam...,In Honor of National Grammar Day,19,OTHER,19.0,0.0,0.0
567,246,407,0.0,Mitigating MonolithsIn freeCodeCampView storyR...,Mitigating Monoliths,50,PM,50.0,0.0,0.0
273,199,454,0.0,Design for doggiesIn freeCodeCampView storyRef...,Design for doggies,334,DES,334.0,0.0,0.0
64,306,347,0.0,Getting a raise comes down to one thing: Lever...,Getting a raise comes down to one thing: Lever...,1.1K,JOB,1100.0,0.0,0.0

# Search into CollTitle column

In [24]:
data[data["CollTitle"].str.contains("time to get in over", case=False)]

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
296,114,539,0.0,It’s time to get in over your headIn freeCodeC...,It’s time to get in over your head,529,MOT,529.0,0.0,0.0
440,106,547,0.0,Code Briefing: It’s time to get in over your h...,Code Briefing: It’s time to get in over your head,42,CB,42.0,0.0,0.0

# Condition

In [27]:
data.loc[data["order"]<200, ["order","CollTitle"] ]

     order                                          CollTitle
1       18  The mind-blowing AI announcement from Google t...
3       94  How to encrypt your entire life in less than a...
5       92  The code I’m still ashamed ofIn freeCodeCampVi...
6       81  I spent 3 months applying to jobs after a codi...
7       73  I can’t just stand by and watch Mark Zuckerber...
..     ...                                                ...
625     25                                      December 2016
626     67                                      November 2016
627    104                                       October 2016
628    154                                     September 2016
629    198                                        August 2016

[199 rows x 2 columns]

In [28]:
data.CollTitle

0      Angular 2 versus React: There Will Be BloodIn ...
1      The mind-blowing AI announcement from Google t...
2      Things I Wish Someone Had Told Me When I Was L...
3      How to encrypt your entire life in less than a...
4      Being A Developer After 40In freeCodeCampView ...
                             ...
647                                        December 2014
648                                        November 2014
649                                         October 2014
650                                        November 2013
651                                         October 2013
Name: CollTitle, Length: 652, dtype: object

# Save to CSV file

In [29]:
data.to_csv("./data/items.csv", index=False)

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 652 entries, 0 to 651
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order           652 non-null    int64
 1   inv-ord         652 non-null    int64
 2   selection       624 non-null    float64
 3   CollTitle       652 non-null    object
 4   CorrectedTitle  652 non-null    object
 5   OrigRecommends  624 non-null    object
 6   classfication   652 non-null    object
 7   Recommends      624 non-null    float64
 8   class_WD        624 non-null    float64
 9   class_WD&CS     624 non-null    float64
dtypes: float64(4), int64(2), object(4)
memory usage: 51.1+ KB

In [32]:
data.tail(2)

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
650,649,4,NaN,November 2013,November 2013,NaN,date,NaN,NaN,NaN
651,651,2,NaN,October 2013,October 2013,NaN,date,NaN,NaN,NaN

In [33]:
data.describe()

           order    inv-ord   selection   Recommends    class_WD  class_WD&CS
count  652.00000  652.00000  624.000000   624.000000  624.000000   624.000000
mean   326.50000  326.50000    0.214744   567.911859    0.230769     0.309295
std    188.36047  188.36047    0.410974  1017.292368    0.421663     0.462574
min      1.00000    1.00000    0.000000     3.000000    0.000000     0.000000
25%    163.75000  163.75000    0.000000    70.750000    0.000000     0.000000
50%    326.50000  326.50000    0.000000   189.000000    0.000000     0.000000
75%    489.25000  489.25000    0.000000   549.250000    0.000000     1.000000
max    652.00000  652.00000    1.000000  7600.000000    1.000000     1.000000

In [35]:
data.shape

(652, 10)

# Select & Filter (2 Min)

In [36]:
data["CollTitle"]

0      Angular 2 versus React: There Will Be BloodIn ...
1      The mind-blowing AI announcement from Google t...
2      Things I Wish Someone Had Told Me When I Was L...
3      How to encrypt your entire life in less than a...
4      Being A Developer After 40In freeCodeCampView ...
                             ...
647                                        December 2014
648                                        November 2014
649                                         October 2014
650                                        November 2013
651                                         October 2013
Name: CollTitle, Length: 652, dtype: object

In [38]:
data[["CollTitle", "order"]]

                                             CollTitle  order
0    Angular 2 versus React: There Will Be BloodIn ...    541
1    The mind-blowing AI announcement from Google t...     18
2    Things I Wish Someone Had Told Me When I Was L...    650
3    How to encrypt your entire life in less than a...     94
4    Being A Developer After 40In freeCodeCampView ...    409
..                                                 ...    ...
647                                      December 2014    636
648                                      November 2014    644
649                                       October 2014    647
650                                      November 2013    649
651                                       October 2013    651

[652 rows x 2 columns]

In [39]:
data.iloc[0]

order                                                           541
inv-ord                                                         112
selection                                                       0.0
CollTitle         Angular 2 versus React: There Will Be BloodIn ...
CorrectedTitle          Angular 2 versus React: There Will Be Blood
OrigRecommends                                                 2.5K
classfication                                                  TECH
Recommends                                                   2500.0
class_WD                                                        0.0
class_WD&CS                                                     0.0
Name: 0, dtype: object

In [40]:
data.iloc[0:2]

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
0,541,112,0.0,Angular 2 versus React: There Will Be BloodIn ...,Angular 2 versus React: There Will Be Blood,2.5K,TECH,2500.0,0.0,0.0
1,18,635,1.0,The mind-blowing AI announcement from Google t...,The mind-blowing AI announcement from Google t...,2.4K,TECH,2400.0,0.0,0.0

In [ ]:
# Filter with order column
data.loc[data["order"]==18]

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
1,18,635,1.0,The mind-blowing AI announcement from Google t...,The mind-blowing AI announcement from Google t...,2.4K,TECH,2400.0,0.0,0.0

In [50]:
# Filter with multiple conditions
data[(data["order"]>250) & (data["OrigRecommends"]=="2.5K") ]

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
0,541,112,0.0,Angular 2 versus React: There Will Be BloodIn ...,Angular 2 versus React: There Will Be Blood,2.5K,TECH,2500.0,0.0,0.0
46,350,303,0.0,Designing in colorIn freeCodeCampView storyRef...,Designing in color,2.5K,DES,2500.0,0.0,0.0

# Modify & Clean (2 Min)

In [51]:
# Add new column
data["Total"]= data["Recommends"]*2.5

In [53]:
data.head()

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS,Total
0,541,112,0.0,Angular 2 versus React: There Will Be BloodIn ...,Angular 2 versus React: There Will Be Blood,2.5K,TECH,2500.0,0.0,0.0,6250.0
1,18,635,1.0,The mind-blowing AI announcement from Google t...,The mind-blowing AI announcement from Google t...,2.4K,TECH,2400.0,0.0,0.0,6000.0
2,650,3,0.0,Things I Wish Someone Had Told Me When I Was L...,Things I Wish Someone Had Told Me When I Was L...,3.2K,MOT,3200.0,0.0,0.0,8000.0
3,94,559,1.0,How to encrypt your entire life in less than a...,How to encrypt your entire life in less than a...,7.4K,SEC,7400.0,0.0,0.0,18500.0
4,409,244,0.0,Being A Developer After 40In freeCodeCampView ...,Being A Developer After 40,6K,MOT,6000.0,0.0,0.0,15000.0

In [54]:
# Drop a column or row
data = data.drop(columns=['Total'])

In [ ]:
# get missing data
data.isna().sum()

order              0
inv-ord            0
selection         28
CollTitle          0
CorrectedTitle     0
OrigRecommends    28
classfication      0
Recommends        28
class_WD          28
class_WD&CS       28
dtype: int64

In [59]:
# Drop rows with missing values
data = data.dropna()

In [60]:
data.head()

,order,inv-ord,selection,CollTitle,CorrectedTitle,OrigRecommends,classfication,Recommends,class_WD,class_WD&CS
0,541,112,0.0,Angular 2 versus React: There Will Be BloodIn ...,Angular 2 versus React: There Will Be Blood,2.5K,TECH,2500.0,0.0,0.0
1,18,635,1.0,The mind-blowing AI announcement from Google t...,The mind-blowing AI announcement from Google t...,2.4K,TECH,2400.0,0.0,0.0
2,650,3,0.0,Things I Wish Someone Had Told Me When I Was L...,Things I Wish Someone Had Told Me When I Was L...,3.2K,MOT,3200.0,0.0,0.0
3,94,559,1.0,How to encrypt your entire life in less than a...,How to encrypt your entire life in less than a...,7.4K,SEC,7400.0,0.0,0.0
4,409,244,0.0,Being A Developer After 40In freeCodeCampView ...,Being A Developer After 40,6K,MOT,6000.0,0.0,0.0

# Group & Aggregate (2 Min)

In [65]:
data.groupby("CollTitle")["order"].mean()
data.groupby("CollTitle").agg({
    'order': ["mean", "max"],
    'Recommends':'min'
})

                                                    order      Recommends
                                                     mean  max        min
CollTitle
10 Principles I Want to Live ByIn freeCodeCampV...   37.0   37     1700.0
10 Steps to Plan Better so you can Write Less C...  615.0  615       62.0
10 Takeaways from 22 Data Visualization Practit...  398.0  398      154.0
10 more podcasts that new coders should listen ...   16.0   16      807.0
10,000 hours! Do you really need that much?In f...  330.0  330       65.0
...                                                   ...  ...        ...
d’Oh My ZshIn freeCodeCampView storyReferrers       457.0  457     1000.0
npm Package Hijacking: From the Hijackers Persp...  453.0  453      304.0
“The Art of Computer Programming” by Donald Knu...  413.0  413     3600.0
“create-react-app” and the future of creating R...  275.0  275      615.0
🎈🎉 The Complete List of User Experience (UX) Re...  486.0  486     1800.0

[620 rows x 3 columns]